### ISSUE TITLE
[로그인 인증 관련] 페이지 오래 머물다가 다른 페이지 갔을때 401뜨는 문제

### ISSUE THREAD

**Issue by Kim-EunKyu** [WakGames/Waktaverse-Games#177]
자세히 얘기하자면 한 페이지에서 로그인된 상태로 토큰이 만료된 후에 다른 페이지로 가면 인증토큰이 없기 때문에 프로필 등의 페이지에서 부르게 되는 api가 401응답을 함.

해당 인증을 하는 구조를 바꿀 필요가 있음

**Comment by NeuroWhAI** [comment]
https://github.com/WakGames/Waktaverse-Games/blob/frontend/frontend/src/utils/api.js 여기에 있는 axios instance 사용된 것이라면 해당 현상이 없어야 정상인데 이상하네요.
아니면 refresh 토큰까지 만료된 상황 말씀하시는 걸까요?

**Comment by Kim-EunKyu** [comment]
@NeuroWhAI 요거는 우선 더 확인이 필요할것같긴한데요, 페이지 오래머물다가 프로필 페이지같은곳에 가니깐 401이 뜬 적이 있어서 우선 이슈 등록했습니다

**Comment by DOS0313** [comment]
그럼 이 Issue 문제 없는거죠?
(문제 없다면 이슈 닫겠습니다)

**Comment by Kim-EunKyu** [comment]
@DOS0313 넵 만약 추후에 발생하면 이슈 다시 열겠습니다.
