### ISSUE TITLE
[랜딩 페이지]  터치패드로 스크롤시 상단에 빈 영역 보임

### ISSUE THREAD

**Issue by Se0nAh** [WakGames/Waktaverse-Games#185]
![Jun-18-2023 00-33-24](https://github.com/WakGames/Waktaverse-Games/assets/49391145/7e5dd32f-aa84-47a7-bb1f-6cf02197a111)

**Comment by kms0219kms** [comment]
그건 브라우저단에서 저렇게 된거라 해결은 못할겁니다. 대신 background를 black으로 줘서 티가 안나게 할 수는 있을거 같아요.

**Comment by DOS0313** [comment]
굳이 필요하지 않을 것으로 예상됨

**Comment by kms0219kms** [comment]
이거 클로즈 할 때 as completed로 하면 안됍니다 @DOS0313
