### ISSUE TITLE
[개발자 포탈] 비 로그인 시 전용 페이지 표시 안됨

### ISSUE THREAD

**Issue by DOS0313** [WakGames/Waktaverse-Games#233]
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/815bc5d1-711d-44bf-a8e4-02505f973840)
테스트 서버 입니다 (https://wakgames-test.neurowhai.cf/intro/devPortal)

(정상 일까요?)

**Comment by markyul** [comment]
테스트한다고 무조건 로그인 된 개발자 포탈로 가게 만들어 놨는데 그 이후 깜빡했습니다.
수정하고 이슈 닫도록 하겠습니다!
