### ISSUE TITLE
[스토어 페이지] 검색 기능 대소문자 구분

### ISSUE THREAD

**Issue by NeuroWhAI** [WakGames/Waktaverse-Games#244]
![image](https://github.com/WakGames/Waktaverse-Games/assets/1130686/eca3ab61-1b5f-4916-a8b1-5de98463cad4)

![image](https://github.com/WakGames/Waktaverse-Games/assets/1130686/0430d0f4-c84e-4fe1-bd76-6bd988fac84f)

큰 이슈는 아니고 영어 대소문자 구분 없이 검색이 되면 더 좋을 것 같아서 이슈 남깁니다.

**Comment by kms0219kms** [comment]
.toLowerCase() 실 검색 처리하는 부분에서 이걸 넣어줄 시면 될겁니다 킹애

**Comment by kms0219kms** [comment]
여담으로 왁제이맥스라고 쳤을 때도 WJMAX가 나오면 좋겠습니다.

**Comment by NeuroWhAI** [comment]
본문(게임 설명)도 검색 대상에 포함하고 잘 검색되도록 본문에 아래와 같이 끝에 추가해주면 어떨까요.

```
(생략) ... 노래를 더 이상 듣기만 하는게 아니라 게임으로 즐겨봅시다.

#왁맥 #왁제이맥스
```
