### ISSUE TITLE
[게임 상세 페이지] 게임 플레이 영상 하이퍼링크 및 하단 마진

### ISSUE THREAD

**Issue by NeuroWhAI** [WakGames/Waktaverse-Games#251]
![image](https://github.com/WakGames/Waktaverse-Games/assets/1130686/9851b256-b17b-4852-ae4c-213cf1c4c4c3)

게임 상세 페이지에 나오는 게임 플레이 영상에 해당 유튜브 링크가 걸려야 할 것 같습니다.
그리고 하단의 "WAKTAVERSE GAMES | NAVER CAFE | SERVER STATUS" 부분과 마진이 있어야 할 것 같습니다.

**Comment by DOS0313** [comment]
해당 부분 진행 시 Figma의 More Info 디자인 적용도 함께 했으면 합니다

**Comment by NeuroWhAI** [comment]
> Figma의 More Info 디자인 적용하면서 같이 적용하면 좋을 것 같습니다

그 저희 More Info는 베타 땐 안 하지 않나요?
우선은 저 UI에서 개선되면 좋을 것 같습니다.
