### ISSUE TITLE
[약관 페이지] 약관 페이지와 R2 연동

### ISSUE THREAD

**Issue by kms0219kms** [WakGames/Waktaverse-Games#283]
1. 개인정보 처리방침 등 약관 페이지와 R2를 연동합니다.
    * 연동 방식: iframe/embed 사용
    * 필요 기능:
        * size 자동 조절(아이프레임 안에 스크롤이 생기지 않도록)
        * 로딩되는 동안 사이즈가 번쩍이며 바뀌지 않도록 initial height 설정 필요
        * 시행일자를 조정할 수 있는 dropdown이 이용약관과 개인정보 처리방침 페이지에 한하여 필요
          ![image](https://github.com/WakGames/Waktaverse-Games/assets/67222970/aac193a3-615a-4779-aa92-a6f27ea94cf0)
     * 문서 요청 URL:
        * 개인정보 처리방침: https://public-r2.waktaverse.games/privacy_notice/시행일자.html or latest.html
        * 이용약관: TBD
        * 오픈소스 라이센스: TBD

**Comment by kms0219kms** [comment]
@markyul

**Comment by DOS0313** [comment]
@markyul 
말씀해주신 iframe 관련해서 반영된 것 같습니다
https://public-r2.waktaverse.games/privacy_notice/latest.html
https://public-r2.waktaverse.games/privacy_notice/20230821.html
