### ISSUE TITLE
[상세 정보 페이지] 디자인 누락

### ISSUE THREAD

**Issue by DOS0313** [WakGames/Waktaverse-Games#325]
현재 배포된 사이트
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/f161a4c5-92fa-422f-a067-421f755a830f)
Figma 디자인
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/209a69e5-4679-4b94-b8b8-27c87eacd062)

공유 버튼 및 신고 버튼이 누락되었습니다

**Comment by markyul** [comment]
있는지 몰랐네요! 그런데 저 자리에 태그가 많으면 + 버튼이 생길텐데 어떡하죠?
<img width="865" alt="image" src="https://github.com/WakGames/Waktaverse-Games/assets/52916848/19cb5c5e-2e9c-454f-b45c-9c320c6283de">

**Comment by DOS0313** [comment]
> 있는지 몰랐네요! 그런데 저 자리에 태그가 많으면 + 버튼이 생길텐데 어떡하죠? <img alt="image" width="865" src="https://user-images.githubusercontent.com/52916848/263547021-19cb5c5e-2e9c-454f-b45c-9c320c6283de.png">

그냥 태그 개수 제한을 둘까요?

**Comment by markyul** [comment]
@DOS0313 그래야할까요..
그런데 모바일이거나 태블릿일때는 저 버튼들 어디로 가나요?

**Comment by DOS0313** [comment]
@markyul 
디자인 완료되었습니다
